CREATING NUMPY ARRAYS

In [6]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
#2d and 3d
b=np.array([[1,2,3],[4,5,6]])
print(b)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#tensor
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#dtype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [25]:
import numpy as np
#with reshape
np.arange(1,11).reshape(5,2)#row*column

#np.ones and np.zeroes
np.ones((3,4))

np.zeros((3,4))

#np.random
np.random.random((3,4)) #random is a class

#np.linspace(linearly spaced)
np.linspace(-10,10,10)#lower range, upper range, no. of items i want to generate
#-10 and 10 e bhetore jei point gulo ache segulor distance same hobe

np.linspace(-10,10,10,dtype=int)


#np.identity
np.identity(3)

#with reshape
np.arange(16).reshape(2,2,2,2)#4d array

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

ARRAY ATTRIBUTES

In [2]:
import numpy as np

a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
a3#tensor....3D array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
#ndim
a1.ndim#1D array
a2.ndim  #2D
a3.ndim  #3D

#shape
a1.shape#1 d numpy array and in one direction there are 10 items
print(a3.shape)#there are 2 2d arrays of 2 rows and 2 columns each



(2, 2, 2)


In [5]:
#size
a3.size#no of items in the array
a2.size

12

In [14]:
#itemsize
a3.itemsize# all are integer inside a3 so its 4 bytes
a1=np.arange(10,dtype=np.int32)# 32 takes 4 bytes, 64 takes 8 bytes
a1.itemsize
print(a1.dtype)
print(a2.dtype)

int32
float64


CHANGING DATATYPE

In [18]:
# astype
a2.dtype
# we need to save our memory
a3.astype(np.int32)#in future a problem might occur in ur dataset where a column might not require so much memory space....here we can use this reduce th size

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

ARRAY OPERATIONS

In [21]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1,a2


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [32]:
#scalar operations
#arithmatic
a1*2
a1-2
a1**2
a1/2
#relational operators
a2>20
a2==15


#vector operations
a1+a2
a1-a2
a1**a2






array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

ARRAY FUNCTIONS

In [33]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[47., 40., 57.],
       [59., 91., 30.],
       [70., 72., 48.]])

In [54]:
#max/min/sum/prod
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.max(a1,axis=1)#max item of every row , 0 means column
np.sum(a1,axis=1)


#mean/median/std/var
np.mean(a1,axis=1)
np.median(a1)
np.std(a1,axis=1)
np.var(a1,axis=1)


#trigonometric functions
np.sin(a1)
np.cos(a1)


#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
a2,a3
np.dot(a2,a3)#matrix multiplication

#log and exponents
np.log(a1)
np.exp(a1)


#round/floor/ceil
np.round(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)



array([[68., 51., 18.],
       [70., 83., 72.]])

INDEXING AND SLICING

In [3]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [78]:
a1[0]
a2[1,2]#row,column
a2[1,0]
a3[1,0,1]#which 2d array,row,column
a3[0,1,0]

2

In [100]:
a1[2:5]
a2[0,:]#first row and all columns
a2[:,2]#3rd column
a2[1:,1:3]#counting starts from 0 
a2[::2,::3]
a2[0::2,1::2]
a2[1,::3]
a2[0:2,1:4]
a3



array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
a3=np.arange(27).reshape(3,3,3)
a3
a3[1]
a3[::2]
a3[0,1,:]
a3[1,2,1]
a3[2,1:,1:]
a3[::2,0,::2]


array([[ 0,  2],
       [18, 20]])

ITERATION

In [4]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [8]:
for i in np.nditer(a3): #converting 3d array to 1 d array and printing it
    print(i)

0
1
2
3
4
5
6
7


RESHAPING

In [10]:
#transpose
np.transpose(a2)
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
#ravel
a2.ravel()#whatever dim an array has it will convert to 1 d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

STACKING

In [16]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a4,a5
np.hstack((a4,a5,a4,a5))


#vertical stacking
np.stack((a4,a5))


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

SPLITING

In [21]:
#horizontal splitting
np.hsplit(a4,2)
np.hsplit(a4,4)


#vertical splitting
np.vsplit(a5,3)



[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]